export const APP_CONFIG = {
  STOP_CALLS_TARGET_SLIDE_INDEX: 3,
  GAME_CHALLENGE_SECONDS: 30,
  GAME_DISCUSSION_SECONDS: 5 * 60,
  STAGE_WIDTH: 1920,
  STAGE_HEIGHT: 1080,
  WARNING_THRESHOLD_SECONDS: 300,
  DANGER_THRESHOLD_SECONDS: 60,
} as const;
